plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-hacker
